COURSE_CATEGORIES = {
    'programming': '💻 Программирование',
    'web': '🌐 Веб-разработка',
    'data_science': '📊 Data Science',
    'mobile': '📱 Мобильная разработка',
    'game_dev': '🎮 Разработка игр',
    'devops': '☁️ DevOps',
    'security': '🔒 Кибербезопасность',
}

COURSES = {
    'programming': [
        {'id': 1, 'title': '🐍 Python для начинающих', 'year': 2023, 'description': 'Полный курс по Python от основ до продвинутых тем.', 'links': [{'title': 'Официальный сайт', 'url': 'https://python.org'}]},
        {'id': 2, 'title': '📜 JavaScript с нуля', 'year': 2022, 'description': 'Изучаем JavaScript и основы веб-разработки.', 'links': [{'title': 'JS Tutorial', 'url': 'https://developer.mozilla.org/en-US/docs/Web/JavaScript'}]},
        {'id': 3, 'title': '🧰 C++ для новичков', 'year': 2021, 'description': 'Основы C++ и объектно-ориентированное программирование.', 'links': [{'title': 'cplusplus.com', 'url': 'http://www.cplusplus.com/doc/tutorial/'}]},
        {'id': 4, 'title': '🔧 Java – базовый курс', 'year': 2020, 'description': 'Изучение Java с нуля до среднего уровня.', 'links': [{'title': 'Oracle Java', 'url': 'https://oracle.com/java'}]},
        {'id': 5, 'title': '⚙️ Go для системного программирования', 'year': 2023, 'description': 'Создание надежных приложений на Go.', 'links': [{'title': 'Go Lang', 'url': 'https://golang.org'}]},
        {'id': 6, 'title': '🌀 Rust – безопасность и скорость', 'year': 2024, 'description': 'Изучаем Rust для высоконагруженных систем.', 'links': [{'title': 'Rust Lang', 'url': 'https://www.rust-lang.org'}]},
        {'id': 7, 'title': '🌐 PHP и MySQL для веба', 'year': 2022, 'description': 'Создаем динамические сайты на PHP.', 'links': [{'title': 'PHP.net', 'url': 'https://www.php.net'}]},
        {'id': 8, 'title': '🐘 PostgreSQL для разработчиков', 'year': 2023, 'description': 'Изучаем базу данных PostgreSQL.', 'links': [{'title': 'PostgreSQL', 'url': 'https://www.postgresql.org'}]},
        {'id': 9, 'title': '🧩 Kotlin для Android', 'year': 2023, 'description': 'Программирование на Kotlin.', 'links': [{'title': 'Kotlin Lang', 'url': 'https://kotlinlang.org'}]},
        {'id': 10, 'title': '☕ Продвинутый Java', 'year': 2023, 'description': 'Углубленное изучение Java и JVM.', 'links': [{'title': 'Java Tutorials', 'url': 'https://docs.oracle.com/javase/tutorial/'}]},
        {'id': 11, 'title': '📱 Swift для iOS', 'year': 2023, 'description': 'Основы программирования на Swift для мобильных приложений.', 'links': [{'title': 'Swift.org', 'url': 'https://swift.org'}]},
        {'id': 12, 'title': '🌟 TypeScript от А до Я', 'year': 2023, 'description': 'Статическая типизация в JavaScript.', 'links': [{'title': 'TypeScript', 'url': 'https://www.typescriptlang.org'}]},
        {'id': 13, 'title': '🛠 Ruby для веб-разработки', 'year': 2021, 'description': 'Основы Ruby и фреймворка Rails.', 'links': [{'title': 'Ruby-lang', 'url': 'https://www.ruby-lang.org'}]},
        {'id': 14, 'title': '🔍 Алгоритмы и структуры данных', 'year': 2023, 'description': 'Ключевые темы CS для разработчиков.', 'links': [{'title': 'GeeksforGeeks', 'url': 'https://www.geeksforgeeks.org/data-structures/'}]},
        {'id': 15, 'title': '⚡ Производительный Python', 'year': 2024, 'description': 'Оптимизация и ускорение кода.', 'links': [{'title': 'Python Docs', 'url': 'https://docs.python.org/3/'}]},
        {'id': 16, 'title': '🧠 Искусственный интеллект для программистов', 'year': 2024, 'description': 'Основы ИИ и машинного обучения.', 'links': [{'title': 'AI Overview', 'url': 'https://en.wikipedia.org/wiki/Artificial_intelligence'}]},
        {'id': 17, 'title': '💾 Базы данных для разработчиков', 'year': 2022, 'description': 'SQL, NoSQL, и их применение.', 'links': [{'title': 'SQL Tutorial', 'url': 'https://sqlzoo.net'}]},
        {'id': 18, 'title': '🕸 Введение в многопоточное программирование', 'year': 2023, 'description': 'Параллелизм и конкурентность.', 'links': [{'title': 'Multithreading', 'url': 'https://docs.oracle.com/javase/tutorial/essential/concurrency/'}]},
        {'id': 19, 'title': '🔌 API: создание и использование', 'year': 2023, 'description': 'REST, GraphQL и другие подходы.', 'links': [{'title': 'REST API Guide', 'url': 'https://restfulapi.net/'}]},
        {'id': 20, 'title': '🧑‍💻 Git: от новичка до профи', 'year': 2023, 'description': 'Контроль версий для командной работы.', 'links': [{'title': 'Git SCM', 'url': 'https://git-scm.com'}]},
        {'id': 21, 'title': '📦 Docker и контейнеризация', 'year': 2023, 'description': 'Создание и управление контейнерами.', 'links': [{'title': 'Docker Docs', 'url': 'https://docs.docker.com/'}]},
        {'id': 22, 'title': '📊 Введение в Big Data', 'year': 2022, 'description': 'Обработка больших данных.', 'links': [{'title': 'Big Data', 'url': 'https://en.wikipedia.org/wiki/Big_data'}]},
        {'id': 23, 'title': '🥷 Продвинутый Python: декораторы и генераторы', 'year': 2023, 'description': 'Углубленное изучение Python.', 'links': [{'title': 'Real Python', 'url': 'https://realpython.com/'}]},
        {'id': 24, 'title': '🧩 Введение в функциональное программирование', 'year': 2021, 'description': 'ФП на примере Haskell и Scala.', 'links': [{'title': 'Learn FP', 'url': 'https://learnyouahaskell.com/'}]},
        {'id': 25, 'title': '🔒 Безопасное программирование', 'year': 2023, 'description': 'Защита кода от уязвимостей.', 'links': [{'title': 'OWASP', 'url': 'https://owasp.org'}]},
        {'id': 26, 'title': '📟 Программирование микроконтроллеров', 'year': 2022, 'description': 'Введение в embedded системы.', 'links': [{'title': 'Microcontrollers', 'url': 'https://www.embedded.com/'}]},
        {'id': 27, 'title': '⏳ Асинхронное программирование в Python', 'year': 2023, 'description': 'asyncio и сопутствующие библиотеки.', 'links': [{'title': 'Asyncio Docs', 'url': 'https://docs.python.org/3/library/asyncio.html'}]},
        {'id': 28, 'title': '🦾 Микросервисы на Python', 'year': 2024, 'description': 'Архитектура и разработка микросервисов.', 'links': [{'title': 'Microservices', 'url': 'https://microservices.io/'}]},
        {'id': 29, 'title': '📚 Паттерны проектирования', 'year': 2022, 'description': 'Обзор классических шаблонов.', 'links': [{'title': 'Design Patterns', 'url': 'https://refactoring.guru/design-patterns'}]},
        {'id': 30, 'title': '⚙️ Разработка CLI приложений', 'year': 2023, 'description': 'Создание утилит командной строки.', 'links': [{'title': 'Python CLI', 'url': 'https://click.palletsprojects.com/'}]},
    ],
    'web': [
        {'id': 101, 'title': '🎨 HTML и CSS', 'year': 2021, 'description': 'Создание современных сайтов, адаптивный дизайн.', 'links': [{'title': 'HTML Tutorial', 'url': 'https://html.spec.whatwg.org/'}]},
        {'id': 102, 'title': '📚 Мастер-класс Webflow 4.0', 'year': 2024, 'description': 'Визуальное создание сайтов с Webflow.', 'links': [{'title': 'Webflow', 'url': 'https://webflow.com'}]},
        {'id': 103, 'title': '⚡ JavaScript для фронтенда', 'year': 2023, 'description': 'Динамические веб-приложения.', 'links': [{'title': 'JS Info', 'url': 'https://javascript.info/'}]},
        {'id': 104, 'title': '🏗 React с нуля', 'year': 2023, 'description': 'Создаем SPA на React.js.', 'links': [{'title': 'React Docs', 'url': 'https://reactjs.org/'}]},
        {'id': 105, 'title': '🚀 Vue.js для начинающих', 'year': 2023, 'description': 'Легкий и мощный фронтенд фреймворк.', 'links': [{'title': 'Vue.js', 'url': 'https://vuejs.org/'}]},
        {'id': 106, 'title': '🛠 Angular для новичков', 'year': 2022, 'description': 'Полный цикл разработки на Angular.', 'links': [{'title': 'Angular', 'url': 'https://angular.io/'}]},
        {'id': 107, 'title': '🗄 Работа с REST API', 'year': 2023, 'description': 'Взаимодействие клиента и сервера.', 'links': [{'title': 'REST API Guide', 'url': 'https://restfulapi.net/'}]},
        {'id': 108, 'title': '📱 Адаптивная вёрстка', 'year': 2023, 'description': 'Создание сайтов, корректно работающих на всех устройствах.', 'links': [{'title': 'MDN CSS', 'url': 'https://developer.mozilla.org/en-US/docs/Web/CSS'}]},
        {'id': 109, 'title': '📈 SEO для разработчиков', 'year': 2023, 'description': 'Оптимизация сайта для поисковых систем.', 'links': [{'title': 'Google SEO', 'url': 'https://developers.google.com/search/docs'}]},
        {'id': 110, 'title': '🖼 Анимации на CSS и JS', 'year': 2022, 'description': 'Улучшение UX с помощью анимаций.', 'links': [{'title': 'CSS Tricks', 'url': 'https://css-tricks.com/'}]},
        {'id': 111, 'title': '🗜 Оптимизация производительности веб-сайтов', 'year': 2023, 'description': 'Ускорение загрузки и рендеринга.', 'links': [{'title': 'Web Performance', 'url': 'https://web.dev/performance/'}]},
        {'id': 112, 'title': '🧩 Web Components', 'year': 2023, 'description': 'Создание переиспользуемых компонентов.', 'links': [{'title': 'Web Components', 'url': 'https://developer.mozilla.org/en-US/docs/Web/Web_Components'}]},
        {'id': 113, 'title': '🧱 Бэкенд для фронтендера', 'year': 2023, 'description': 'Введение в Node.js и Express.', 'links': [{'title': 'Node.js', 'url': 'https://nodejs.org/'}]},
        {'id': 114, 'title': '🛡 Веб-безопасность', 'year': 2023, 'description': 'Защита сайтов от уязвимостей.', 'links': [{'title': 'OWASP Top 10', 'url': 'https://owasp.org/www-project-top-ten/'}]},
        {'id': 115, 'title': '🔌 GraphQL', 'year': 2023, 'description': 'Современный подход к API.', 'links': [{'title': 'GraphQL', 'url': 'https://graphql.org/'}]},
        {'id': 116, 'title': '⚙️ Webpack и сборщики', 'year': 2023, 'description': 'Автоматизация сборки проекта.', 'links': [{'title': 'Webpack', 'url': 'https://webpack.js.org/'}]},
        {'id': 117, 'title': '🧑‍💻 JAMstack', 'year': 2023, 'description': 'Современная архитектура веба.', 'links': [{'title': 'JAMstack', 'url': 'https://jamstack.org/'}]},
        {'id': 118, 'title': '📢 Progressive Web Apps', 'year': 2023, 'description': 'Веб-приложения с функционалом нативных.', 'links': [{'title': 'PWA', 'url': 'https://web.dev/progressive-web-apps/'}]},
        {'id': 119, 'title': '🖥 Web Accessibility', 'year': 2022, 'description': 'Доступность сайтов для всех пользователей.', 'links': [{'title': 'Accessibility', 'url': 'https://www.w3.org/WAI/'}]},
        {'id': 120, 'title': '📦 Создание npm-пакетов', 'year': 2023, 'description': 'Распространение своих библиотек.', 'links': [{'title': 'npm Docs', 'url': 'https://docs.npmjs.com/'}]},
        {'id': 121, 'title': '🌍 Международные веб-приложения', 'year': 2023, 'description': 'Локализация и интернационализация.', 'links': [{'title': 'I18n', 'url': 'https://www.i18next.com/'}]},
        {'id': 122, 'title': '🧪 Тестирование фронтенда', 'year': 2023, 'description': 'Jest, Cypress и другие инструменты.', 'links': [{'title': 'Testing Library', 'url': 'https://testing-library.com/'}]},
        {'id': 123, 'title': '⚡ SSR и SSG', 'year': 2023, 'description': 'Server-side rendering и статическая генерация.', 'links': [{'title': 'Next.js', 'url': 'https://nextjs.org/'}]},
        {'id': 124, 'title': '🌐 HTTP/3 и современные протоколы', 'year': 2024, 'description': 'Новейшие веб-технологии сети.', 'links': [{'title': 'HTTP/3', 'url': 'https://http3check.net/'}]},
        {'id': 125, 'title': '🔧 Chrome DevTools', 'year': 2023, 'description': 'Отладка и инспекция сайтов.', 'links': [{'title': 'Chrome DevTools', 'url': 'https://developer.chrome.com/docs/devtools/'}]},
        {'id': 126, 'title': '🗃 Redis для веб-разработки', 'year': 2023, 'description': 'Кэширование и хранение данных.', 'links': [{'title': 'Redis', 'url': 'https://redis.io/'}]},
        {'id': 127, 'title': '🛠 CSS Grid и Flexbox', 'year': 2023, 'description': 'Современные техники вёрстки.', 'links': [{'title': 'CSS Tricks', 'url': 'https://css-tricks.com/snippets/css/complete-guide-grid/'}]},
        {'id': 128, 'title': '⏳ Оптимизация загрузки изображений', 'year': 2022, 'description': 'Lazy loading и современные форматы.', 'links': [{'title': 'Image Optimization', 'url': 'https://web.dev/fast/#images'}]},
        {'id': 129, 'title': '🎥 Видео и аудио на сайтах', 'year': 2023, 'description': 'HTML5 и JavaScript медиа.', 'links': [{'title': 'MDN Media', 'url': 'https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery'}]},
        {'id': 130, 'title': '🔍 Аналитика и веб-метрики', 'year': 2023, 'description': 'Google Analytics, Яндекс.Метрика.', 'links': [{'title': 'Google Analytics', 'url': 'https://analytics.google.com/'}]},
    ],
    'data_science': [
        {'id': 201, 'title': '📈 Введение в Data Science', 'year': 2023, 'description': 'Основы анализа данных и машинного обучения.', 'links': [{'title': 'Kaggle', 'url': 'https://kaggle.com'}]},
        {'id': 202, 'title': '🤖 Машинное обучение с Python', 'year': 2023, 'description': 'Scikit-learn, Pandas и Matplotlib.', 'links': [{'title': 'Scikit-learn', 'url': 'https://scikit-learn.org/'}]},
        {'id': 203, 'title': '📊 Анализ данных с Pandas', 'year': 2023, 'description': 'Обработка и визуализация данных.', 'links': [{'title': 'Pandas Docs', 'url': 'https://pandas.pydata.org/'}]},
        {'id': 204, 'title': '🌟 Глубокое обучение', 'year': 2024, 'description': 'Нейронные сети и TensorFlow.', 'links': [{'title': 'TensorFlow', 'url': 'https://www.tensorflow.org/'}]},
        {'id': 205, 'title': '📉 Статистика для Data Science', 'year': 2023, 'description': 'Теория вероятностей и статистические методы.', 'links': [{'title': 'Statistical Methods', 'url': 'https://www.khanacademy.org/math/statistics-probability'}]},
        {'id': 206, 'title': '🔥 NLP: обработка естественного языка', 'year': 2023, 'description': 'Техники обработки текста.', 'links': [{'title': 'NLTK', 'url': 'https://www.nltk.org/'}]},
        {'id': 207, 'title': '🌐 Работа с большими данными', 'year': 2024, 'description': 'Hadoop, Spark и экосистемы.', 'links': [{'title': 'Apache Spark', 'url': 'https://spark.apache.org/'}]},
        {'id': 208, 'title': '🧮 Математика для Data Science', 'year': 2023, 'description': 'Линейная алгебра и вычисления.', 'links': [{'title': 'Linear Algebra', 'url': 'https://www.khanacademy.org/math/linear-algebra'}]},
        {'id': 209, 'title': '📚 Визуализация данных', 'year': 2023, 'description': 'Matplotlib, Seaborn, Plotly.', 'links': [{'title': 'Plotly', 'url': 'https://plotly.com/python/'}]},
        {'id': 210, 'title': '🎯 Рекомендательные системы', 'year': 2023, 'description': 'Создание систем рекомендаций.', 'links': [{'title': 'Recommender Systems', 'url': 'https://developers.google.com/machine-learning/recommendation/'}]},
        {'id': 211, 'title': '📦 Data Engineering', 'year': 2024, 'description': 'Обработка данных и дата-пайплайны.', 'links': [{'title': 'Data Engineering', 'url': 'https://dataengineering.org/'}]},
        {'id': 212, 'title': '🧠 Искусственные нейронные сети', 'year': 2023, 'description': 'Основы и архитектуры.', 'links': [{'title': 'Neural Networks', 'url': 'https://www.deeplearning.ai/'}]},
        {'id': 213, 'title': '🔍 Анализ временных рядов', 'year': 2023, 'description': 'Прогнозирование и методики.', 'links': [{'title': 'Time Series', 'url': 'https://otexts.com/fpp3/'}]},
        {'id': 214, 'title': '💡 Feature Engineering', 'year': 2023, 'description': 'Подготовка данных для моделей.', 'links': [{'title': 'Feature Engineering', 'url': 'https://www.kdnuggets.com/2019/11/feature-engineering.html'}]},
        {'id': 215, 'title': '🧹 Обработка отсутствующих данных', 'year': 2023, 'description': 'Методы и подходы.', 'links': [{'title': 'Handling Missing Data', 'url': 'https://www.analyticsvidhya.com/blog/2016/03/tutorial-powerful-packages-imputing-missing-values-python/'}]},
        {'id': 216, 'title': '🔬 Data Science с R', 'year': 2023, 'description': 'Применение R для аналитики.', 'links': [{'title': 'R Project', 'url': 'https://www.r-project.org/'}]},
        {'id': 217, 'title': '🔄 Кросс-валидация и оценка моделей', 'year': 2023, 'description': 'Методы проверки качества.', 'links': [{'title': 'Cross-validation', 'url': 'https://scikit-learn.org/stable/modules/cross_validation.html'}]},
        {'id': 218, 'title': '🐍 Python для продвинутой аналитики', 'year': 2023, 'description': 'Расширенные возможности анализа.', 'links': [{'title': 'Advanced Python', 'url': 'https://realpython.com/advanced-python/'}]},
        {'id': 219, 'title': '📦 ML Ops', 'year': 2024, 'description': 'Деплой и сопровождение моделей.', 'links': [{'title': 'MLOps', 'url': 'https://ml-ops.org/'}]},
        {'id': 220, 'title': '👁️ Computer Vision', 'year': 2023, 'description': 'Обработка и анализ изображений.', 'links': [{'title': 'OpenCV', 'url': 'https://opencv.org/'}]},
        {'id': 221, 'title': '📉 Регрессия и классификация', 'year': 2023, 'description': 'Основы supervised learning.', 'links': [{'title': 'ML Basics', 'url': 'https://www.coursera.org/learn/machine-learning'}]},
        {'id': 222, 'title': '🤖 Обучение с подкреплением', 'year': 2024, 'description': 'Reinforcement Learning.', 'links': [{'title': 'RL Intro', 'url': 'http://incompleteideas.net/book/the-book.html'}]},
        {'id': 223, 'title': '✨ Введение в AutoML', 'year': 2023, 'description': 'Автоматизация ML процессов.', 'links': [{'title': 'AutoML Guide', 'url': 'https://www.automl.org/'}]},
        {'id': 224, 'title': '🧠 TensorFlow для новичков', 'year': 2023, 'description': 'Построение моделей нейросетей.', 'links': [{'title': 'TensorFlow', 'url': 'https://www.tensorflow.org/'}]},
        {'id': 225, 'title': '🔍 EDA: исследовательский анализ данных', 'year': 2023, 'description': 'Методы визуализации и понимания данных.', 'links': [{'title': 'EDA Tutorial', 'url': 'https://towardsdatascience.com/exploratory-data-analysis-8fc1cb20fd15'}]},
        {'id': 226, 'title': '📦 Data Visualization с D3.js', 'year': 2023, 'description': 'Создание интерактивных графиков.', 'links': [{'title': 'D3.js', 'url': 'https://d3js.org/'}]},
        {'id': 227, 'title': '📊 Tableau для визуализации', 'year': 2023, 'description': 'Инструмент бизнес-аналитики.', 'links': [{'title': 'Tableau', 'url': 'https://www.tableau.com/'}]},
        {'id': 228, 'title': '🚀 Big Data с Apache Kafka', 'year': 2024, 'description': 'Обработка потоков данных.', 'links': [{'title': 'Kafka', 'url': 'https://kafka.apache.org/'}]},
        {'id': 229, 'title': '💾 Хранение данных и базы', 'year': 2023, 'description': 'NoSQL базы и их применение.', 'links': [{'title': 'MongoDB', 'url': 'https://www.mongodb.com/'}]},
        {'id': 230, 'title': '🧮 Байесовские методы в Data Science', 'year': 2023, 'description': 'Статистическая обработка и прогнозирование.', 'links': [{'title': 'Bayesian Methods', 'url': 'https://www.coursera.org/learn/bayesian'}]},
    ],
    'mobile': [
        {'id': 301, 'title': '📲 Разработка Android приложений', 'year': 2023, 'description': 'Создаем приложения на Kotlin и Android Studio.', 'links': [{'title': 'Android Dev', 'url': 'https://developer.android.com'}]},
        {'id': 302, 'title': '📱 iOS разработка на Swift', 'year': 2023, 'description': 'Создание приложений для iPhone и iPad.', 'links': [{'title': 'Swift', 'url': 'https://swift.org'}]},
        {'id': 303, 'title': '🛠 Flutter для кроссплатформенной разработки', 'year': 2023, 'description': 'Создаем приложения для Android и iOS.', 'links': [{'title': 'Flutter', 'url': 'https://flutter.dev'}]},
        {'id': 304, 'title': '🤖 React Native', 'year': 2023, 'description': 'Мобильная разработка на базе React.', 'links': [{'title': 'React Native', 'url': 'https://reactnative.dev/'}]},
        {'id': 305, 'title': '📡 Работа с API на мобильных устройствах', 'year': 2023, 'description': 'Интеграция с веб-сервисами.', 'links': [{'title': 'API Mobile', 'url': 'https://developer.android.com/training/volley'}]},
        {'id': 306, 'title': '📦 Управление состоянием в мобильных приложениях', 'year': 2023, 'description': 'Redux, Bloc и другие подходы.', 'links': [{'title': 'State Management', 'url': 'https://flutter.dev/docs/development/data-and-backend/state-mgmt/intro'}]},
        {'id': 307, 'title': '🎨 Дизайн интерфейсов для мобильных', 'year': 2023, 'description': 'UX/UI лучшие практики.', 'links': [{'title': 'Material Design', 'url': 'https://material.io/design'}]},
        {'id': 308, 'title': '📈 Оптимизация производительности мобильных приложений', 'year': 2023, 'description': 'Ускорение загрузки и отрисовки.', 'links': [{'title': 'Android Performance', 'url': 'https://developer.android.com/topic/performance'}]},
        {'id': 309, 'title': '🔍 Тестирование мобильных приложений', 'year': 2023, 'description': 'Unit, UI и интеграционные тесты.', 'links': [{'title': 'Testing Flutter', 'url': 'https://flutter.dev/docs/testing'}]},
        {'id': 310, 'title': '🔓 Безопасность мобильных приложений', 'year': 2023, 'description': 'Шифрование, защита данных.', 'links': [{'title': 'Mobile Security', 'url': 'https://owasp.org/www-project-mobile-security-testing-guide/'}]},
        {'id': 311, 'title': '🧰 Xamarin для кроссплатформенной разработки', 'year': 2022, 'description': 'C# для Android и iOS.', 'links': [{'title': 'Xamarin', 'url': 'https://dotnet.microsoft.com/apps/xamarin'}]},
        {'id': 312, 'title': '🌐 Progressive Web Apps для мобильных', 'year': 2023, 'description': 'WEB-приложения с функциями нативных.', 'links': [{'title': 'PWA', 'url': 'https://web.dev/progressive-web-apps/'}]},
        {'id': 313, 'title': '📊 Аналитика мобильных приложений', 'year': 2023, 'description': 'Инструменты для отслеживания событий.', 'links': [{'title': 'Firebase Analytics', 'url': 'https://firebase.google.com/products/analytics'}]},
        {'id': 314, 'title': '💾 Локальное хранение данных', 'year': 2023, 'description': 'SQLite, Realm и SharedPreferences.', 'links': [{'title': 'SQLite', 'url': 'https://www.sqlite.org/index.html'}]},
        {'id': 315, 'title': '🚀 Publising mobile apps', 'year': 2022, 'description': 'Загрузка приложений в App Store и Google Play.', 'links': [{'title': 'Publishing Guide', 'url': 'https://developer.apple.com/app-store/'}]},
        {'id': 316, 'title': '🔨 Инструменты разработки мобильных приложений', 'year': 2023, 'description': 'IDE, эмуляторы и профайлеры.', 'links': [{'title': 'Android Studio', 'url': 'https://developer.android.com/studio'}]},
        {'id': 317, 'title': '📱 Анимации в мобильных приложениях', 'year': 2023, 'description': 'Улучшаем UX через анимации.', 'links': [{'title': 'Animation Guide', 'url': 'https://flutter.dev/docs/development/ui/animations'}]},
        {'id': 318, 'title': '🕹 Игры на мобильных платформах', 'year': 2023, 'description': 'Создание игр для Android/iOS.', 'links': [{'title': 'Unity Mobile', 'url': 'https://unity.com/mobile-development'}]},
        {'id': 319, 'title': '📡 Push-уведомления и их настройка', 'year': 2023, 'description': 'Работа с Push Notification.', 'links': [{'title': 'Firebase Cloud Messaging', 'url': 'https://firebase.google.com/docs/cloud-messaging'}]},
        {'id': 320, 'title': '🧪 Beta-тестирование мобильных приложений', 'year': 2023, 'description': 'Работа с TestFlight и Google Play Console.', 'links': [{'title': 'TestFlight', 'url': 'https://developer.apple.com/testflight/'}]},
        {'id': 321, 'title': '🛡 Лицензирование и защита приложений', 'year': 2023, 'description': 'Антипиратские механизмы.', 'links': [{'title': 'Mobile App Security', 'url': 'https://owasp.org/www-project-mobile-security-testing-guide/'}]},
        {'id': 322, 'title': '⚡ Работа с Bluetooth и NFC', 'year': 2023, 'description': 'Интеграция с аппаратными возможностями.', 'links': [{'title': 'Android Bluetooth', 'url': 'https://developer.android.com/guide/topics/connectivity/bluetooth'}]},
        {'id': 323, 'title': '🎤 Голосовые команды для мобильных приложений', 'year': 2023, 'description': 'Использование распознавания голоса.', 'links': [{'title': 'Speech Recognition', 'url': 'https://developer.apple.com/documentation/speech'}]},
        {'id': 324, 'title': '🧩 Использование ARKit и ARCore', 'year': 2023, 'description': 'Дополненная реальность в мобильных приложениях.', 'links': [{'title': 'ARKit', 'url': 'https://developer.apple.com/augmented-reality/arkit/'}]},
        {'id': 325, 'title': '📲 Работы с камерой и мультимедиа', 'year': 2023, 'description': 'Съемка фото и видео.', 'links': [{'title': 'Android Camera', 'url': 'https://developer.android.com/guide/topics/media/camera'}]},
        {'id': 326, 'title': '🧱 Архитектура мобильных приложений', 'year': 2023, 'description': 'MVVM, MVP и Clean Architecture.', 'links': [{'title': 'Mobile Architecture', 'url': 'https://developer.android.com/jetpack/guide'}]},
        {'id': 327, 'title': '🕵️‍♂️ Анализ производительности', 'year': 2023, 'description': 'Профайлинг и оптимизация.', 'links': [{'title': 'Android Profiler', 'url': 'https://developer.android.com/studio/profile'}]},
        {'id': 328, 'title': '🎯 Разработка под носимые устройства', 'year': 2023, 'description': 'Умные часы и фитнес-браслеты.', 'links': [{'title': 'Wear OS', 'url': 'https://wearos.google.com/'}]},
        {'id': 329, 'title': '🛠 Инструменты CI/CD для мобильных', 'year': 2023, 'description': 'Автоматизация сборки и доставки.', 'links': [{'title': 'Fastlane', 'url': 'https://fastlane.tools/'}]},
        {'id': 330, 'title': '📚 Курсы подготовки к сертификациям Android и iOS', 'year': 2023, 'description': 'Сертификации и экзамены.', 'links': [{'title': 'Google Certification', 'url': 'https://developers.google.com/certification/android'}]},
    ],
    'game_dev': [
        {'id': 401, 'title': '🎮 Введение в Unity', 'year': 2022,
         'description': 'Основы разработки игр на движке Unity.',
         'links': [{'title': 'Unity', 'url': 'https://unity.com'}]},
        {'id': 402, 'title': '🕹 Разработка игр на Unreal Engine', 'year': 2023,
         'description': 'Высококачественная визуализация и геймплей.',
         'links': [{'title': 'Unreal Engine', 'url': 'https://www.unrealengine.com/'}]},
        {'id': 403, 'title': '🎨 Создание 2D игр', 'year': 2023, 'description': 'Пиксельная графика и анимация.',
         'links': [{'title': '2D Game Dev', 'url': 'https://learn.unity.com/course/2d-game-kit'}]},
        {'id': 404, 'title': '🛠 Программирование геймплея', 'year': 2023, 'description': 'Логика и взаимодействия.',
         'links': [{'title': 'Game Programming', 'url': 'https://www.gamedev.net/'}]},
        {'id': 405, 'title': '📦 Работа с физикой в играх', 'year': 2023,
         'description': 'Реалистичные движения и столкновения.',
         'links': [{'title': 'Unity Physics', 'url': 'https://docs.unity3d.com/Manual/PhysicsSection.html'}]},
        {'id': 406, 'title': '🦾 AI для игр', 'year': 2023, 'description': 'Поведение NPC и врагов.',
         'links': [{'title': 'Game AI', 'url': 'https://aiandgames.com/'}]},
        {'id': 407, 'title': '🌐 Мультиплеерные игры', 'year': 2023, 'description': 'Сетевой код и синхронизация.',
         'links': [{'title': 'Multiplayer', 'url': 'https://www.photonengine.com/'}]},
        {'id': 408, 'title': '🎯 Оптимизация игр', 'year': 2023, 'description': 'Улучшение производительности.',
         'links': [
             {'title': 'Game Optimization', 'url': 'https://developer.valvesoftware.com/wiki/Game_Optimization'}]},
        {'id': 409, 'title': '🎬 Создание кат-сцен и анимаций', 'year': 2023,
         'description': 'Интеграция видео и анимаций.',
         'links': [{'title': 'Unity Timeline', 'url': 'https://docs.unity3d.com/Manual/TimelineSection.html'}]},
        {'id': 410, 'title': '📢 Звуковое оформление игр', 'year': 2023, 'description': 'Работа со звуком и музыкой.',
         'links': [{'title': 'Game Audio', 'url': 'https://www.audiokinetic.com/'}]},
        {'id': 411, 'title': '🛠 Инструменты разработки игр', 'year': 2023, 'description': 'IDE, движки и плагины.',
         'links': [{'title': 'Game Dev Tools', 'url': 'https://gamedevtools.io/'}]},
        {'id': 412, 'title': '🔧 Сценарии и скрипты на C# для Unity', 'year': 2023,
         'description': 'Создание логики персонажей и мира.',
         'links': [{'title': 'Unity C# Scripting', 'url': 'https://docs.unity3d.com/Manual/ScriptingSection.html'}]},
        {'id': 413, 'title': '💾 Сохранение и загрузка данных', 'year': 2023,
         'description': 'Работа с сохранениями игры.', 'links': [
            {'title': 'Game Data Persistence', 'url': 'https://learn.unity.com/tutorial/saving-and-loading-data'}]},
        {'id': 414, 'title': '🎮 Создание интерфейсов HUD', 'year': 2023, 'description': 'UI/UX для игр.',
         'links': [{'title': 'Unity UI', 'url': 'https://docs.unity3d.com/Manual/UISystem.html'}]},
        {'id': 415, 'title': '🚀 Выпуск игр на мобильные платформы', 'year': 2023,
         'description': 'Публикация и оптимизация.',
         'links': [{'title': 'Build and Release', 'url': 'https://docs.unity3d.com/Manual/PublishingBuilds.html'}]},
        {'id': 416, 'title': '🎲 Разработка настольных игр', 'year': 2022, 'description': 'Правила, логика и прототипы.',
         'links': [{'title': 'Board Games Dev', 'url': 'https://boardgamegeek.com/'}]},
        {'id': 417, 'title': '🧩 Моделирование персонажей и активов', 'year': 2023,
         'description': '3D-модели и текстуры.', 'links': [{'title': 'Blender', 'url': 'https://www.blender.org/'}]},
        {'id': 418, 'title': '🕹 VR и AR в играх', 'year': 2024, 'description': 'Дополненная и виртуальная реальность.',
         'links': [{'title': 'VR Dev', 'url': 'https://developer.oculus.com/'}]},
        {'id': 419, 'title': '📈 Аналитика игровых данных', 'year': 2023,
         'description': 'Отслеживание поведения игроков.',
         'links': [{'title': 'Game Analytics', 'url': 'https://gameanalytics.com/'}]},
        {'id': 420, 'title': '🔥 Мультиплатформенная разработка', 'year': 2023,
         'description': 'Игры на различные устройства.',
         'links': [{'title': 'Cross Platform', 'url': 'https://unity.com/cross-platform'}]},
        {'id': 421, 'title': '🔮 Создание процедурных миров', 'year': 2023,
         'description': 'Генерация уровней и объектов.', 'links': [{'title': 'Procedural Generation',
                                                                    'url': 'https://www.gamasutra.com/view/feature/131515/procedural_content_generation.php'}]},
        {'id': 422, 'title': '💡 Проектирование уровней', 'year': 2023, 'description': 'Дизайн карт и миссий.',
         'links': [{'title': 'Level Design', 'url': 'https://www.gamasutra.com/view/feature/132545/level_design.php'}]},
        {'id': 423, 'title': '🎥 Интеграция видео и кат-сцен', 'year': 2023,
         'description': 'Пример создания видео вставок.',
         'links': [{'title': 'Video in Unity', 'url': 'https://docs.unity3d.com/Manual/VideoPlayer.html'}]},
        {'id': 424, 'title': '🎧 Звуковое программирование', 'year': 2023,
         'description': 'Динамическая генерация звуков.', 'links': [{'title': 'FMOD', 'url': 'https://www.fmod.com/'}]},
        {'id': 425, 'title': '🗺 Создание открытых миров', 'year': 2024, 'description': 'Техника и оптимизация.',
         'links': [{'title': 'Open World Design',
                    'url': 'https://gamedevelopment.tutsplus.com/articles/designing-open-world-levels--gamedev-14253'}]},
        {'id': 426, 'title': '📜 Сценарное и повествовательное проектирование', 'year': 2023,
         'description': 'Создание историй и сюжета.', 'links': [{'title': 'Narrative Design',
                                                                 'url': 'https://www.gamasutra.com/view/feature/130888/storytelling_in_video_games.php'}]},
        {'id': 427, 'title': '🚀 Оптимизация сборки и загрузки', 'year': 2023,
         'description': 'Уменьшаем размер и ускоряем загрузку.',
         'links': [{'title': 'Build Optimization', 'url': 'https://docs.unity3d.com/Manual/OptimizingYourGame.html'}]},
        {'id': 428, 'title': '🔍 Тестирование игр', 'year': 2023, 'description': 'QA-процессы и инструменты.',
         'links': [{'title': 'Game Testing', 'url': 'https://www.gamedeveloper.com/programming/testing-in-games'}]},
        {'id': 429, 'title': '🧩 Инструменты для инди-разработчиков', 'year': 2023,
         'description': 'Простые решения и движки.',
         'links': [{'title': 'Indie Game Dev', 'url': 'https://www.indiegamedev.net/'}]},
        {'id': 430, 'title': '🖌 Художественное оформление игр', 'year': 2023,
         'description': 'Иллюстрация и концепт-арт.',
         'links': [{'title': 'Game Art', 'url': 'https://conceptartempire.com/game-art/'}]},
    ],

    'devops': [
        {'id': 501, 'title': '☁️ DevOps с нуля', 'year': 2023,
         'description': 'CI/CD, контейнеры и автоматизация инфраструктуры.',
         'links': [{'title': 'Docker', 'url': 'https://docker.com'}]},
        {'id': 502, 'title': '🔧 Kubernetes для начинающих', 'year': 2023, 'description': 'Оркестрация контейнеров.',
         'links': [{'title': 'Kubernetes', 'url': 'https://kubernetes.io/'}]},
        {'id': 503, 'title': '⚙️ Jenkins и автоматизация', 'year': 2023, 'description': 'Построение конвейеров сборки.',
         'links': [{'title': 'Jenkins', 'url': 'https://www.jenkins.io/'}]},
        {'id': 504, 'title': '🛡 Безопасность в DevOps', 'year': 2023, 'description': 'Практики SecOps.',
         'links': [{'title': 'DevSecOps', 'url': 'https://www.devsecops.org/'}]},
        {'id': 505, 'title': '📦 CI/CD с GitHub Actions', 'year': 2023, 'description': 'Автоматизация в GitHub.',
         'links': [{'title': 'GitHub Actions', 'url': 'https://github.com/features/actions'}]},
        {'id': 506, 'title': '📡 Мониторинг с Prometheus и Grafana', 'year': 2023,
         'description': 'Отслеживание системы и алерты.',
         'links': [{'title': 'Prometheus', 'url': 'https://prometheus.io/'}]},
        {'id': 507, 'title': '🧹 Управление конфигурацией с Ansible', 'year': 2023,
         'description': 'Автоматизация настройки серверов.',
         'links': [{'title': 'Ansible', 'url': 'https://www.ansible.com/'}]},
        {'id': 508, 'title': '⚡ Terraform для инфраструктуры', 'year': 2023, 'description': 'Infrastructure as Code.',
         'links': [{'title': 'Terraform', 'url': 'https://www.terraform.io/'}]},
        {'id': 509, 'title': '🚀 Docker Compose и оркестрация', 'year': 2023,
         'description': 'Управление многоконтейнерными приложениями.',
         'links': [{'title': 'Docker Compose', 'url': 'https://docs.docker.com/compose/'}]},
        {'id': 510, 'title': '🔍 Логирование с ELK Stack', 'year': 2023, 'description': 'Centralized log management.',
         'links': [{'title': 'ELK Stack', 'url': 'https://www.elastic.co/elk-stack'}]},
        {'id': 511, 'title': '🕵️‍♂️ Секреты и управление чувствительными данными', 'year': 2023,
         'description': 'Vault, Sealed Secrets.',
         'links': [{'title': 'HashiCorp Vault', 'url': 'https://www.vaultproject.io/'}]},
        {'id': 512, 'title': '🛠 Автоматизация тестирования', 'year': 2023,
         'description': 'Интеграционное и e2e тестирование.', 'links': [{'title': 'Automated Testing',
                                                                         'url': 'https://www.softwaretestinghelp.com/automation-testing-tutorial-1/'}]},
        {'id': 513, 'title': '🌐 Балансировка нагрузки', 'year': 2023, 'description': 'NGINX, HAProxy и другие.',
         'links': [{'title': 'Load Balancing', 'url': 'https://www.nginx.com/resources/glossary/load-balancing/'}]},
        {'id': 514, 'title': '⚙️ Облачные платформы: AWS', 'year': 2023, 'description': 'Основы Amazon Web Services.',
         'links': [{'title': 'AWS', 'url': 'https://aws.amazon.com/'}]},
        {'id': 515, 'title': '☁️ Облачные платформы: Azure', 'year': 2023, 'description': 'Microsoft Azure для DevOps.',
         'links': [{'title': 'Azure', 'url': 'https://azure.microsoft.com/'}]},
        {'id': 516, 'title': '☁️ Облачные платформы: GCP', 'year': 2023,
         'description': 'Google Cloud Platform особенности.',
         'links': [{'title': 'GCP', 'url': 'https://cloud.google.com/'}]},
        {'id': 517, 'title': '🛡 Контейнерная безопасность', 'year': 2023, 'description': 'Сканирование и hardening.',
         'links': [{'title': 'Container Security', 'url': 'https://sysdig.com/blog/container-security/'}]},
        {'id': 518, 'title': '📜 Скрипты и автоматизация на Bash', 'year': 2023,
         'description': 'Облегчаем рутинные задачи.',
         'links': [{'title': 'Bash Scripting', 'url': 'https://linuxconfig.org/bash-scripting-tutorial'}]},
        {'id': 519, 'title': '🔄 Обновления и деплой без простоя', 'year': 2023,
         'description': 'Blue/Green и Canary деплой.',
         'links': [{'title': 'Deployment Strategies', 'url': 'https://martinfowler.com/articles/bluegreen.html'}]},
        {'id': 520, 'title': '📦 Управление артефактами и пакетами', 'year': 2023, 'description': 'Nexus, Artifactory.',
         'links': [{'title': 'Artifact Repositories', 'url': 'https://www.sonatype.com/nexus-repository-sonatype'}]},
        {'id': 521, 'title': '🧰 Helm для Kubernetes', 'year': 2023, 'description': 'Менеджер пакетов для K8s.',
         'links': [{'title': 'Helm', 'url': 'https://helm.sh/'}]},
        {'id': 522, 'title': '🖥 Виртуализация с VMware и KVM', 'year': 2023, 'description': 'Создание и управление ВМ.',
         'links': [{'title': 'VMware', 'url': 'https://www.vmware.com/'}]},
        {'id': 523, 'title': '📚 Докеризация приложений', 'year': 2023,
         'description': 'Создание эффективных Dockerfile.', 'links': [{'title': 'Dockerfile Best Practices',
                                                                       'url': 'https://docs.docker.com/develop/develop-images/dockerfile_best-practices/'}]},
        {'id': 524, 'title': '📈 Метрики и SLA', 'year': 2023, 'description': 'Мониторинг и поддержка SLA.', 'links': [
            {'title': 'Service Level Agreement', 'url': 'https://en.wikipedia.org/wiki/Service-level_agreement'}]},
        {'id': 525, 'title': '☁️ Serverless архитектуры', 'year': 2023, 'description': 'AWS Lambda, Azure Functions.',
         'links': [{'title': 'Serverless', 'url': 'https://www.serverless.com/'}]},
        {'id': 526, 'title': '🌍 Сетевые технологии для DevOps', 'year': 2023, 'description': 'Протоколы, VPN и прокси.',
         'links': [
             {'title': 'Networking Basics', 'url': 'https://www.cloudflare.com/learning/network-layer/what-is-vpn/'}]},
        {'id': 527, 'title': '🧩 Инфраструктура как код', 'year': 2023, 'description': 'Pulumi, CloudFormation.',
         'links': [{'title': 'Infrastructure as Code', 'url': 'https://www.pulumi.com/'}]},
        {'id': 528, 'title': '🕹 Автоматизация игровых серверов', 'year': 2023,
         'description': 'CI/CD для игровых проектов.',
         'links': [{'title': 'Game Server DevOps', 'url': 'https://multiplay.com/'}]},
        {'id': 529, 'title': '⚙️ Настройка CI в GitLab', 'year': 2023, 'description': 'Автоматизация сборок и тестов.',
         'links': [{'title': 'GitLab CI', 'url': 'https://docs.gitlab.com/ee/ci/'}]},
        {'id': 530, 'title': '🛡 Управление уязвимостями', 'year': 2023, 'description': 'Сканеры и процессы фиксации.',
         'links': [{'title': 'Vulnerability Management',
                    'url': 'https://www.tenable.com/products/tenable-io/vulnerability-management'}]},
    ],

    'security': [
        {'id': 601, 'title': '🔐 Основы кибербезопасности', 'year': 2023,
         'description': 'Защита информации, криптография и атаки.',
         'links': [{'title': 'OWASP', 'url': 'https://owasp.org'}]},
        {'id': 602, 'title': '🛡 Пентестинг для новичков', 'year': 2023, 'description': 'Тестирование на проникновение.',
         'links': [{'title': 'Pentesting', 'url': 'https://www.offensive-security.com/'}]},
        {'id': 603, 'title': '🔍 Анализ уязвимостей', 'year': 2023, 'description': 'Инструменты и подходы.',
         'links': [{'title': 'Vulnerability Scanning', 'url': 'https://www.tenable.com/products/nessus'}]},
        {'id': 604, 'title': '⚙️ Безопасность веб-приложений', 'year': 2023, 'description': 'XSS, CSRF и SQL-инъекции.',
         'links': [{'title': 'OWASP Top 10', 'url': 'https://owasp.org/www-project-top-ten/'}]},
        {'id': 605, 'title': '📜 Криптография для разработчиков', 'year': 2023,
         'description': 'Шифрование данных и протоколы.',
         'links': [{'title': 'Cryptography', 'url': 'https://cryptography.io/en/latest/'}]},
        {'id': 606, 'title': '🚨 Реагирование на инциденты', 'year': 2023, 'description': 'Процессы и анализ атак.',
         'links': [{'title': 'Incident Response', 'url': 'https://www.sans.org/incident-response'}]},
        {'id': 607, 'title': '🕵️‍♂️ Социальная инженерия', 'year': 2023, 'description': 'Методы и защита.',
         'links': [{'title': 'Social Engineering', 'url': 'https://www.social-engineer.com/'}]},
        {'id': 608, 'title': '📡 Сетевая безопасность', 'year': 2023, 'description': 'Firewall, IDS и IPS.', 'links': [
            {'title': 'Network Security',
             'url': 'https://www.cisco.com/c/en/us/products/security/what-is-network-security.html'}]},
        {'id': 609, 'title': '🧑‍💻 Разработка безопасного кода', 'year': 2023, 'description': 'Secure coding practices.',
         'links': [{'title': 'Secure Coding',
                    'url': 'https://owasp.org/www-project-secure-coding-practices-quick-reference-guide/'}]},
        {'id': 610, 'title': '🔒 Управление доступом и IAM', 'year': 2023,
         'description': 'Роли, политики и аутентификация.',
         'links': [{'title': 'IAM', 'url': 'https://aws.amazon.com/iam/'}]},
        {'id': 611, 'title': '🛡 Безопасность мобильных приложений', 'year': 2023,
         'description': 'Особенности и уязвимости.', 'links': [
            {'title': 'Mobile Security', 'url': 'https://owasp.org/www-project-mobile-security-testing-guide/'}]},
        {'id': 612, 'title': '📦 Управление уязвимостями', 'year': 2023, 'description': 'Использование сканеров.',
         'links': [{'title': 'Vulnerability Management',
                    'url': 'https://www.tenable.com/products/tenable-io/vulnerability-management'}]},
        {'id': 613, 'title': '🔑 Аутентификация и авторизация', 'year': 2023, 'description': 'OAuth, JWT, SAML.',
         'links': [{'title': 'Auth Protocols', 'url': 'https://oauth.net/'}]},
        {'id': 614, 'title': '🛡 Защита сетевой инфраструктуры', 'year': 2023,
         'description': 'VPN, протоколы безопасности.', 'links': [{'title': 'Network Protection',
                                                                   'url': 'https://www.cisco.com/c/en/us/products/security/vpn-endpoint-security-clients/index.html'}]},
        {'id': 615, 'title': '🐳 Безопасность контейнеров', 'year': 2023, 'description': 'Практики и инструменты.',
         'links': [{'title': 'Container Security', 'url': 'https://sysdig.com/blog/container-security/'}]},
        {'id': 616, 'title': '📊 Мониторинг безопасности', 'year': 2023, 'description': 'SIEM и логирование.', 'links': [
            {'title': 'SIEM',
             'url': 'https://www.splunk.com/en_us/solutions/solution-areas/security-information-event-management.html'}]},
        {'id': 617, 'title': '🚫 Защита от DDoS атак', 'year': 2023, 'description': 'Методы и сервисы.',
         'links': [{'title': 'DDoS Protection', 'url': 'https://aws.amazon.com/ddos-protection/'}]},
        {'id': 618, 'title': '🔍 Анализ вредоносных программ', 'year': 2023,
         'description': 'Обратный инжиниринг и детектирование.',
         'links': [{'title': 'Malware Analysis', 'url': 'https://www.sans.org/course/malware-analysis'}]},
        {'id': 619, 'title': '🧑‍💼 Соответствие стандартам и GDPR', 'year': 2023,
         'description': 'Регуляции и политика безопасности.',
         'links': [{'title': 'GDPR', 'url': 'https://gdpr-info.eu/'}]},
        {'id': 620, 'title': '💾 Резервное копирование и восстановление', 'year': 2023, 'description': 'Best practices.',
         'links': [{'title': 'Backup Guidelines',
                    'url': 'https://www.nist.gov/itl/nist-800-34-contingency-planning-guide-information-technology-systems'}]},
        {'id': 621, 'title': '🧰 Инструменты для пентестеров', 'year': 2023, 'description': 'Metasploit, Nmap и др.',
         'links': [{'title': 'Metasploit', 'url': 'https://www.metasploit.com/'}]},
        {'id': 622, 'title': '⚙️ Безопасность облачных сервисов', 'year': 2023, 'description': 'AWS, Azure, GCP.',
         'links': [{'title': 'Cloud Security', 'url': 'https://cloudsecurityalliance.org/'}]},
        {'id': 623, 'title': '🔐 Шифрование и протоколы безопасности', 'year': 2023, 'description': 'SSL/TLS, VPN.',
         'links': [{'title': 'TLS', 'url': 'https://tools.ietf.org/html/rfc5246'}]},
        {'id': 624, 'title': '🕵️‍♂️ Социальная инженерия и фишинг', 'year': 2023, 'description': 'Обучение и защита.',
         'links': [{'title': 'Phishing Awareness', 'url': 'https://www.phishing.org/'}]},
        {'id': 625, 'title': '📡 Безопасность IoT устройств', 'year': 2023, 'description': 'Вызовы и решения.',
         'links': [{'title': 'IoT Security', 'url': 'https://www.iotforall.com/iot-security-challenges-solutions'}]},
        {'id': 626, 'title': '🌐 Безопасность сетей Wi-Fi', 'year': 2023, 'description': 'WPA3, атаки и защита.',
         'links': [{'title': 'WiFi Security', 'url': 'https://www.wi-fi.org/discover-wi-fi/security'}]},
        {'id': 627, 'title': '📝 Политики безопасности и стандарты', 'year': 2023, 'description': 'ISO 27001 и другие.',
         'links': [{'title': 'ISO 27001', 'url': 'https://www.iso.org/isoiec-27001-information-security.html'}]},
        {'id': 628, 'title': '🛡 Работа с SIEM системами', 'year': 2023, 'description': 'Анализ событий безопасности.',
         'links': [{'title': 'Splunk', 'url': 'https://www.splunk.com/'}]},
        {'id': 629, 'title': '🔍 Форензика и расследование инцидентов', 'year': 2023,
         'description': 'Цепочка доказательств и анализ.',
         'links': [{'title': 'Digital Forensics', 'url': 'https://www.sans.org/course/mobile-device-forensics'}]},
        {'id': 630, 'title': '🎯 Анализ поведения и обнаружение угроз', 'year': 2023, 'description': 'SIEMs и UEBA.',
         'links': [{'title': 'Threat Detection',
                    'url': 'https://www.crowdstrike.com/epp-101/endpoint-detection-response-edr/'}]},
    ],
}